# Generated by Django 4.2 on 2023-04-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='is_user',
        ),
        migrations.AddField(
            model_name='login',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
