# Generated by Django 4.2 on 2023-04-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_login_is_user_login_is_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='is_customer',
            new_name='is_user',
        ),
    ]
