# Generated by Django 4.2 on 2023-04-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_attachments_remove_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='attachment',
            field=models.FileField(default=True, upload_to='uploads/'),
        ),
    ]
