# Generated by Django 4.2 on 2023-04-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_create_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='attachment',
            new_name='profile',
        ),
    ]
