# Generated by Django 4.2 on 2023-04-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_attachment_create_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='profile',
        ),
    ]
