# Generated by Django 4.2 on 2023-04-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_tasks_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_lists',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
    ]
