# Generated by Django 4.2 on 2023-04-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tasks_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='create',
            name='username',
        ),
    ]
