# Generated by Django 4.2 on 2023-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
