# Generated by Django 4.2 on 2023-05-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_add_lists_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_lists',
            name='project',
        ),
    ]
