# Generated by Django 4.2 on 2023-05-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_lists',
            name='project',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_list', to='app.projects'),
        ),
    ]
