# Generated by Django 4.2 on 2023-05-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_add_lists_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium '), ('high', 'High')], max_length=200),
        ),
    ]
